# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=100)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=9.99, max_digits=100, null=True)),
            ],
        ),
    ]
