# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='managers',
            field=models.ManyToManyField(related_name='managers_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
