# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170816_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='type',
            field=models.CharField(choices=[('hd', 'HD'), ('sd', 'SD'), ('micro', 'Micro')], default='hd', max_length=20),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='media',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=products.models.thumbnail_location, width_field='width'),
        ),
    ]
