# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='products',
            new_name='product',
        ),
    ]
